name: Allure

on:
  push:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3
          
      - name: Get Test Results history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Create Playwright Test Results History
        uses: PavanMudigonda/allure-html-reporter-github-pages@v1.0
        if: always()
        id: allure-report
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_ID: allure.yml
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with: 
            authToken: ${{secrets.GITHUB_TOKEN}}
            context: 'Test Results Link'
            state: 'success'
            sha: ${{ github.sha }}
            target_url: https://PavanMudigonda.github.io/allure-html-reporter-github-pages/${{ github.run_number }}
